### ISSUE TITLE
Require to implement Pagination for launched instances.

### ISSUE THREAD

**Issue by jaeko44** [megamsys/nilavu#1094]
For dashboard, we add a search bar (unstyled -> I will Style it) that can search for their launched vms, apps.

For vms we allow them to search by IP, or by Name label, and operating system (for services and apps: they can search by the software used - for example WordPress or MySQL as well as name & IP)

We also add pagination to each section (vms , apps, services) when there are more than 10 instances per section (Virtual Machines, Apps, Services are all individual sections). And split it to 10 instances per pagination or whatever you guys think is reasonable to make it uncluttered.

**Comment by indykish** [comment]
@rajthilakmca  The fix is to implement as follows.

## controller

Refer this. 
https://github.com/discourse/discourse/blob/master/app/assets/javascripts/admin/controllers/admin-group.js.es6

Controller manages the current `offset, limit` and user interaction of `next/previous`.

## model

https://github.com/discourse/discourse/blob/master/app/assets/javascripts/admin/controllers/admin-group.js.es6

model has the data, and total rows.

## template

shows like `1/10`
https://github.com/discourse/discourse/blob/master/app/assets/javascripts/admin/templates/group.hbs

your limit will be configured in site_settings as `topic_scroll_limit: 10`. 

Yeah `topic` - `tribute to discourse`.

**Comment by indykish** [comment]
A temporary hack with a button "Show More" is added in the dash.

Fixed in https://gitlab.com/megamsys/nilavu.git (MegamVertice/VirtEngine - Complete Edition)
